### ISSUE TITLE
Error upon installation

### ISSUE THREAD

**Issue by pcav** [adrianaksan/qgis-mongodb-plugin#4]
Just a generic: invalid syntax

**Comment by pcav** [comment]
More explanation from subsequent error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/.qgis2/python/plugins/qgis-mongodb-loader/**init**.py", line 34, in classFactory
    from .loadMongoDB import loadMongoDB
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.qgis2/python/plugins/qgis-mongodb-loader/loadMongoDB.py", line 14, in 
    import resources_rc, os.path, pymongo, json
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named pymongo

**Comment by pcav** [comment]
aptitude install python-pymongo does not solve it.
Dependencies should be clearly stated in the About, so users will know before installing.

**Comment by adrianaksan** [comment]
Hi, I've made some corrections but I am unable to upload the fix for the "invalid syntax" error which is being caused by the hyphenated folder name. I receive the following message when I try to upload the change:

Plugin name mismatch: the plugin main folder name in the compressed file (qgis_mongodb_plugin) is different from the original plugin package name (qgis-mongodb-loader).

**Comment by pcav** [comment]
I confirm, plugin and folder must be the same. Please note that repeating "plugin" is unnecessary, and discouraged, see: http://plugins.qgis.org/

**Comment by adrianaksan** [comment]
Hi, sorry I mean that I need to make the correction below:

Plugin name mismatch: the plugin main folder name in the compressed file (qgis_mongodb_loader) is different from the original plugin package name (qgis-mongodb-loader).

This is to prevent the "syntax" error due to non Pep8 compliant naming of the folder:
https://www.python.org/dev/peps/pep-0008/

**Comment by adrianaksan** [comment]
Sorry, the error is actually:

duplicate key value violates unique constraint "plugins_plugin_name_key" DETAIL: Key (name)=(Load MongoDB Layers) already exists.

**Comment by adrianaksan** [comment]
I'm trying to upload qgis_mongodb_loader instead of qgis-mongodb-loader.

**Comment by jugoslaviaa** [comment]
I´m getting errors during the installation as well. I´d like to know, wheter the plugin works properly right now. 
The error I got is "Couldn't load plugin qgis-mongodb-loader due to an error when calling its classFactory() method"

**Comment by corinis** [comment]
I was able to fix the issue by symlinking the folder. 

```
cd ~/.qgis2/python/plugins
ln -s qgis-mongodb-loader/ qgis_mongodb_loader
```

just renaming did not work: then it couldnt find the cache.txt

**Comment by adrianaksan** [comment]
As per corinis notes, the issue might have been resolved. Please advise if this persist and I will reopen it/ provide a permanent fix.
